'use client';
import { FormEvent, useEffect, useState } from 'react';
import { CaseResponse, DocumentResponse, MosaicApi, VerificationRunResponse } from '../lib/mosaic-api';
import { clearAccessToken, getAccessToken } from '../lib/officer-session';
import { OfficerLogin } from './officer-login';
import { VerificationResults } from './verification-results';

export function OfficerWorkflow({ api }: { api: MosaicApi }) {
 const [token,setToken]=useState<string|null>(null),[caseItem,setCase]=useState<CaseResponse|null>(null),[title,setTitle]=useState(''),[tender,setTender]=useState<File|null>(null),[bidders,setBidders]=useState<File[]>([]),[documents,setDocuments]=useState<DocumentResponse[]>([]),[run,setRun]=useState<VerificationRunResponse|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{const id=window.setTimeout(()=>setToken(getAccessToken()),0);return()=>window.clearTimeout(id);},[]);
 useEffect(()=>{ if (!run || !token || !['queued','running'].includes(run.status)) return; const id=window.setTimeout(async()=>{try {setRun(await api.getVerification(token,run.id));}catch(e){setError(e instanceof Error?e.message:'Unable to poll verification');}},1500); return()=>window.clearTimeout(id);},[api,run,token]);
 async function create(event:FormEvent){event.preventDefault();if(!token)return;setBusy(true);try{setCase(await api.createCase(token,{tender_title:title}));}catch(e){setError(e instanceof Error?e.message:'Unable to create case');}finally{setBusy(false)}}
 async function upload(){if(!token||!caseItem||!tender)return;setBusy(true);setError(null);try{const uploaded=[await api.uploadDocument(token,caseItem.id,'tender',tender),...await Promise.all(bidders.map(file=>api.uploadDocument(token,caseItem.id,'bidder',file)))];setDocuments(uploaded);}catch(e){setError(e instanceof Error?e.message:'Unable to upload document');}finally{setBusy(false)}}
 async function start(){if(!token||!caseItem)return;setBusy(true);try{setRun(await api.startVerification(token,caseItem.id));}catch(e){setError(e instanceof Error?e.message:'Unable to start verification');}finally{setBusy(false)}}
 if(!token)return <OfficerLogin api={api} onAuthenticated={()=>setToken(getAccessToken())}/>;
 return <div className="space-y-6"><button className="text-sm underline" onClick={()=>{clearAccessToken();setToken(null)}}>Sign out</button>{!caseItem?<form onSubmit={create} className="space-y-3"><label>Tender title<input aria-label="Tender title" value={title} onChange={e=>setTitle(e.target.value)} required minLength={3}/></label><button disabled={busy}>Create case</button></form>:<section className="space-y-3"><p>Case: {caseItem.tender_title}</p><label>Tender PDF<input aria-label="Tender PDF" type="file" accept="application/pdf" onChange={e=>setTender(e.target.files?.[0]??null)}/></label><label>Bidder PDFs<input aria-label="Bidder PDFs" type="file" multiple accept="application/pdf" onChange={e=>setBidders(Array.from(e.target.files??[]))}/></label>{[tender,...bidders].filter(Boolean).some(f=>f!.type!=='application/pdf')?<p role="alert">PDF files only</p>:null}<button onClick={upload} disabled={busy||!tender||!bidders.length}>Upload documents</button>{documents.length?<ul>{documents.map(doc=><li key={doc.id}>{doc.original_filename}: {doc.processing_status}</li>)}</ul>:null}<button onClick={start} disabled={busy||documents.filter(d=>d.kind==='tender').length!==1||!documents.some(d=>d.kind==='bidder')}>Start verification</button></section>}{error?<p role="alert">{error}</p>:null}{run?<VerificationResults run={run}/>:null}</div>;
}
